### ISSUE TITLE
ReferenceField not displaying

### ISSUE THREAD

**Issue by ihrigb** [simokhalil/ra-data-json-hal#1]
Hi, not sure, if this is still maintained.

When I use a `ReferenceField` as follows, it is not showing up.

```javascript
<ReferenceField source="_links.teacher.href" reference="teachers" label="Teacher">
  <TextField source="name" />
</ReferenceField>
```

**Comment by simokhalil** [comment]
Hi @ihrigb 

I'm sorry, I have no time to look at this for now. I will try tonight and come back to you ASAP.

**Comment by ihrigb** [comment]
I got an idea on what is going wrong. When I have a record as following

```json
{
  "_embedded": {
    "student_name": "Joe",
    "student_id": "1"
  },
  "_links": {
    "self": {
      "href": "http://localhost:8080/students/1"
    },
    "teacher": {
      "href": "http://localhost:8080/students/1/teacher"
    }
  }
}
```
Then react-admin will do a `GET_MANY` with query `{"id": ["http://localhost:8080/students/1/teacher"]}`. ra-data-json-hal is able to execute this request and return the record, but now with a differnt id, which may be something like `xyz` (populated from the self link).
I believe this missmatch causes issues in react-admin to properly display the data.

**Comment by nwflte** [comment]
Hi, been debugging this same issue but to no avail, everything seems fine but displaying it isn't:
```JSX 
<ReferenceField label="User" source="_links.user.href" reference="users">
        <TextField source="username" />
</ReferenceField>
```

I then get records from getMany():
```javascript 
{
data: [{
  id: "2",
  username: "username",
   password: "$2a$10$87m..",
],
}
```

Have you found something on this? Thanks
