### ISSUE TITLE
Wrong version of code on npmjs.com!

### ISSUE THREAD

**Issue by uchqunbek** [simokhalil/ra-data-json-hal#2]
Hi!
There your code is 👍, but on "ra-data-json-hal" package on fetch.js file wrong link to constants file. 

```var _constants = require('../src/constants');```

Can you republish your package with correct linking?

**Comment by simokhalil** [comment]
Hi !

The package named "ra-data-json-hal" on npmjs is not mine, so I cannot publish with the same package name there.

I actually made this repo to fix this require issue (and some others) on the original "ra-data-json-hal" package, for a project I was working for. So if you want to use this version, you can install it directly from Github, like 

```
npm install https://github.com/simokhalil/ra-data-json-hal
```
or using yarn

```
yarn add https://github.com/simokhalil/ra-data-json-hal
```

**Comment by andrinheusser** [comment]
A note about that in the README would be nice.
